/* Generated By:JavaCC: Do not edit this line. XML_parserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XML_parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 1;
  /** RegularExpression Id. */
  int LBLCABECERA = 7;
  /** RegularExpression Id. */
  int VERSION = 8;
  /** RegularExpression Id. */
  int NUMEROV = 9;
  /** RegularExpression Id. */
  int ENCODING = 10;
  /** RegularExpression Id. */
  int TIPO = 11;
  /** RegularExpression Id. */
  int DOC = 12;
  /** RegularExpression Id. */
  int ARCHIVO = 13;
  /** RegularExpression Id. */
  int IETQ_ASIGNATURAS = 14;
  /** RegularExpression Id. */
  int IETQ_NUEVA_ASIGNATURA = 15;
  /** RegularExpression Id. */
  int IETQ_PROFESOR = 16;
  /** RegularExpression Id. */
  int IETQ_ALUMNOS = 17;
  /** RegularExpression Id. */
  int IETQ_ALUMNO = 18;
  /** RegularExpression Id. */
  int IETQ_NOMBRE = 19;
  /** RegularExpression Id. */
  int IETQ_MAIL = 20;
  /** RegularExpression Id. */
  int IETQ_RESUMEN = 21;
  /** RegularExpression Id. */
  int FETQ_ASIGNATURAS = 22;
  /** RegularExpression Id. */
  int FETQ_NUEVA_ASIGNATURA = 23;
  /** RegularExpression Id. */
  int FETQ_PROFESOR = 24;
  /** RegularExpression Id. */
  int FETQ_ALUMNOS = 25;
  /** RegularExpression Id. */
  int FETQ_ALUMNO = 26;
  /** RegularExpression Id. */
  int FETQ_NOMBRE = 27;
  /** RegularExpression Id. */
  int FETQ_MAIL = 28;
  /** RegularExpression Id. */
  int FETQ_RESUMEN = 29;
  /** RegularExpression Id. */
  int CONTENIDO = 30;
  /** RegularExpression Id. */
  int HELPER_CONTENIDO = 31;
  /** RegularExpression Id. */
  int MAIL_STRUCTURE = 32;
  /** RegularExpression Id. */
  int MAIL_SINGLE_LINE = 33;
  /** RegularExpression Id. */
  int NOMBRE_SINGLE_LINE = 34;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 2>",
    "\"<!--\"",
    "\"<!--\"",
    "\"-->\"",
    "<token of kind 6>",
    "<LBLCABECERA>",
    "<VERSION>",
    "<NUMEROV>",
    "<ENCODING>",
    "<TIPO>",
    "<DOC>",
    "<ARCHIVO>",
    "\"<Asignaturas>\"",
    "<IETQ_NUEVA_ASIGNATURA>",
    "\"<Profesor>\"",
    "\"<Alumnos>\"",
    "\"<Alumno>\"",
    "\"<Nombre>\"",
    "\"<Mail>\"",
    "\"<Resumen>\"",
    "\"</Asignaturas>\"",
    "<FETQ_NUEVA_ASIGNATURA>",
    "\"</Profesor>\"",
    "\"</Alumnos>\"",
    "\"</Alumno>\"",
    "\"</Nombre>\"",
    "\"</Mail>\"",
    "\"</Resumen>\"",
    "<CONTENIDO>",
    "<HELPER_CONTENIDO>",
    "<MAIL_STRUCTURE>",
    "<MAIL_SINGLE_LINE>",
    "<NOMBRE_SINGLE_LINE>",
  };

}
